# Units for easy adjustability
units:
    # Proxy spacing variables
    # TODO: use uppercase U for slightly bigger?
    kx: u
    ky: u

    # Padding variables
    pad: 3
    half_x: (cx / 2)
    half_y: (cy / 2)
    half_x_padded: half_x + pad
    half_y_padded: half_y + pad
    half_x_antipad: half_x - pad
    half_y_antipad: half_y - pad

# Layout of keyboard
points:
    rotate: -15
    mirror:
        ref: matrix_inner_top
        distance: 4kx
    zones:
        matrix:
            key:
                # Propagate any change to the default spacing
                padding: ky
                spread: kx
            columns:
                outer:
                    key:
                        stagger: 0
                pinky:
                    key:
                        stagger: 0
                ring:
                    key:
                        stagger: 8
                middle:
                    key:
                        stagger: 5
                index:
                    key:
                        stagger: -6
                inner:
                    key:
                        stagger: -3
                    rows.mod.skip: true
            rows:
                mod:
                bottom:
                home:
                top:
            anchor:
                # Shift PCB into KiCAD frame
                shift: [100, -150]
        thumb:
            key:
                # Propagate any change to the default spacing
                padding: ky
                spread: kx
            anchor:
                # Anchor on zone "matrix", column "innerinner", row "mod"
                ref: matrix_inner_mod
                # TODO: consider this carefully
                shift: [14, -12]
            columns:
                inner:
                    key:
                        # Rotate thumb cluster
                        # TODO: consider this carefully
                        splay: -20
                        height: 1.5kx
                outer:
                    key.height: 1.5kx
            rows.first:

# Case outlines
outlines:
    # Just a rectangle around the keys, for vis
    keys:
        - what: rectangle
          where: true
          size: [kx, ky]
    # Left case - mirrored below
    board_left:
        - what: polygon
          operation: stack
          fillet: 2
          points:
            # Start top left, go clockwise
            - ref: matrix_outer_top
              shift: [-half_x_padded, half_y_padded]
            # Go along fingers to guarantee case follows no matter what stagger values are
            - ref: matrix_outer_top
              shift: [half_x_antipad, half_y_padded]
            - ref: matrix_pinky_top
              shift: [-half_x_padded, half_y_padded]
            - ref: matrix_pinky_top
              shift: [half_x_antipad, half_y_padded]
            - ref: matrix_ring_top
              shift: [-half_x_padded, half_y_padded]
            - ref: matrix_ring_top
              shift: [half_x_antipad, half_y_padded]
            - ref: matrix_middle_top
              shift: [-half_x_padded, half_y_padded]
            - ref: matrix_middle_top
              shift: [half_x_padded, half_y_padded]
            - ref: matrix_index_top
              shift: [-half_x_antipad, half_y_padded]
            - ref: matrix_index_top
              shift: [half_x_padded, half_y_padded]
            - ref: matrix_index_top
              shift: [kx + half_x_padded, half_y_padded]
            # Down right of matrix_inner_bottom
            - ref: matrix_inner_bottom
              shift: [half_x_padded, -half_y_padded]
            - ref: thumb_outer_first
              # TODO: change to use half_y_padded if thumb goes back to normal-sized key
              shift: [half_x_padded, 1.5*half_y + pad]
            - ref: thumb_outer_first
              # TODO: change to use half_y_padded if thumb goes back to normal-sized key
              shift: [half_x_padded, -(1.5*half_y + pad)]
            - ref: thumb_inner_first
              # TODO: change to use half_y_padded if thumb goes back to normal-sized key
              shift: [-half_x_padded, -(1.5*half_y + pad)]
            # Down right of matrix_index_mod (incl. pad), forms a straight line across the bottom of the case.
            # Use y position of outer col key to guarantee that straight line.
            - ref: matrix_outer_mod
              shift: [half_x + 4kx, -half_y_padded]
            - ref: matrix_outer_mod
              shift: [-half_x_padded, -half_y_padded]

    # NOTE: to re-produce this after changes to board_left:
    # 1) copy and replace matrix with mirror_matrix and thumb with mirror_thumb
    # 2) comments: delete OR flip right/left, clockwise/counterclockwise, etc.
    # 3) DON'T flip sign of x values in "shift" pairs as this is done w/ the mirror
    board_right:
        - what: polygon
          operation: stack
          fillet: 2
          points:
            # Start top right, go counterclockwise
            - ref: mirror_matrix_outer_top
              shift: [-half_x_padded, half_y_padded]
            # Go along fingers to guarantee case follows no matter what stagger values are
            - ref: mirror_matrix_outer_top
              shift: [half_x_antipad, half_y_padded]
            - ref: mirror_matrix_pinky_top
              shift: [-half_x_padded, half_y_padded]
            - ref: mirror_matrix_pinky_top
              shift: [half_x_antipad, half_y_padded]
            - ref: mirror_matrix_ring_top
              shift: [-half_x_padded, half_y_padded]
            - ref: mirror_matrix_ring_top
              shift: [half_x_antipad, half_y_padded]
            - ref: mirror_matrix_middle_top
              shift: [-half_x_padded, half_y_padded]
            - ref: mirror_matrix_middle_top
              shift: [half_x_padded, half_y_padded]
            - ref: mirror_matrix_index_top
              shift: [-half_x_antipad, half_y_padded]
            - ref: mirror_matrix_index_top
              shift: [half_x_padded, half_y_padded]
            - ref: mirror_matrix_index_top
              shift: [kx + half_x_padded, half_y_padded]
            # Down left of mirror_matrix_inner_bottom
            - ref: mirror_matrix_inner_bottom
              shift: [half_x_padded, -half_y_padded]
            - ref: mirror_thumb_outer_first
              # TODO: change to use half_y_padded if thumb goes back to normal-sized key
              shift: [half_x_padded, 1.5*half_y + pad]
            - ref: mirror_thumb_outer_first
              # TODO: change to use half_y_padded if thumb goes back to normal-sized key
              shift: [half_x_padded, -(1.5*half_y + pad)]
            - ref: mirror_thumb_inner_first
              # TODO: change to use half_y_padded if thumb goes back to normal-sized key
              shift: [-half_x_padded, -(1.5*half_y + pad)]
            # Down left of mirror_matrix_index_mod (incl. pad), forms a straight line across the bottom of the case.
            # Use y position of outer col key to guarantee that straight line.
            - ref: mirror_matrix_outer_mod
              shift: [half_x + 4kx, -half_y_padded]
            - ref: mirror_matrix_outer_mod
              shift: [-half_x_padded, -half_y_padded]
    # Combination preview showing outline and keys.
    combo:
        - name: board_left
        - operation: subtract
          name: keys

pcbs:
    left:
        outlines:
            main:
                outline: board_left
            keycaps:
                outline: keys
        footprints:
            mx_hotswap:
                what: mx
                # Just left side, no mirror
                where: /^(thumb|matrix)_.*/
                params:
                    keycaps: true
                    reverse: false
                    hotswap: true
                    from: "{{column_net}}"
                    to: "{{colrow}}"
                adjust:
                    # TODO: keep from caldera?
                    rotate: 180
            nice_nano:
                what: nice_nano
                params.orientation: up
                where:
                    ref: matrix_inner_top
            diode_main:
                what: diode
                # TODO: like caldera, move some diodes for mounting holes?
                where: /^(thumb|matrix)_.*/
                params:
                    from: "{{colrow}}"
                    to: "{{row_net}}"
                adjust:
                    shift: [-1.9, 5.65]
